PipelineSecrets:
  DockerConfig: '{"auths":{"uwdcicdaks01.azurecr.io":{"auth":"dXdkY2ljZGFrczAxOnBtN2sxODNQeFJOREVacFk1akdubnN3YVcwY0toSFA9"}}}'
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: jx-dev.quickplay.com
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: uwdcicdaks01.azurecr.io
        TILLER_NAMESPACE: kube-system
prow: {}
